language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-pandas python-cvxopt
install:
  - pip install .
script:
  - python portfolioopt/test_portfolioopt.py
